### ISSUE TITLE
No matches 

### ISSUE THREAD

**Issue by sevapp** [britzl/emthree#5]
Hello! Is it possible to somehow avoid the situation with the lack of combinations and shuffle the board? I would like to be able to automatically detect the absence of combinations and shuffle the board =)

<img width="431" alt="Screenshot 2022-11-14 at 7 54 29 PM" src="https://user-images.githubusercontent.com/18247732/201733908-35860bc7-fb89-4cab-9b3c-9ae8adb7499c.png">

**Comment by britzl** [comment]
I've added support for checking for a board with no matches.

`emthree.on_no_possible_switches(board, fn)`

**Comment by britzl** [comment]
And a basic `emthree.shuffle(board)`

**Comment by sevapp** [comment]
Thank you so much! ^_^
